version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2182:2181'
  kafka:
    image: 'wurstmeister/kafka:2.12-2.2.1'
    ports:
      - '9092:9092'
      - '1099:1099'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      JMX_PORT: '1099'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
  device-app:
    image: 'device-app:latest'
    environment:
      PG_URL: jdbc:postgresql://db:5432/db
      PG_USER: postgres
      PG_PASSWORD: admin
    ports:
      - '8081:8080'
    links:
      - db
  receiver-app:
    image: 'receiver-app:latest'
    environment:
      PG_URL: jdbc:postgresql://db:5432/db
      PG_USER: postgres
      PG_PASSWORD: admin
      KAFKA_HOST: kafka:9092
      KAFKA_TOPIC: lot4-messages
    ports:
      - '8082:8080'
    links:
      - db
      - kafka
  sender-app:
    image: 'sender-app:latest'
    environment:
      KAFKA_HOST: kafka:9092
      KAFKA_TOPIC: lot4-messages
    ports:
      - '8083:8080'
    links:
      - kafka
  statistic-app:
    image: 'statistic-app:latest'
    environment:
      PG_URL: jdbc:postgresql://db:5432/db
      PG_USER: postgres
      PG_PASSWORD: admin
    ports:
      - '8084:8080'
    links:
      - db