version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2182:2181'
  kafka:
    image: 'wurstmeister/kafka:2.12-2.2.1'
    ports:
      - '9092:9092'
      - '1099:1099'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_CREATE_TOPICS: 'lot4_notify:1:1,lot4_messages:1:1'
      JMX_PORT: '1099'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      GRAYLOG_HOST: graylog
      GRAYLOG_PORT: '12201'
    ports:
      - '5432:5432'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
  device-app:
    image: 'device-app:latest'
    environment:
      PG_URL: jdbc:postgresql://db:5432/db
      PG_USER: postgres
      PG_PASSWORD: admin
      GRAYLOG_HOST: graylog
      GRAYLOG_PORT: '12201'
    ports:
      - '8081:8080'
    links:
      - db

  notify-app:
    image: 'notify-app:latest'
    environment:
      KAFKA_HOST: kafka:9092
      KAFKA_TOPIC: lot4_notify
      GRAYLOG_HOST: graylog
      GRAYLOG_PORT: '12201'
    ports:
      - '8085:8080'
    links:
      - kafka
      - graylog

  receiver-app:
    image: 'receiver-app:latest'
    environment:
      PG_URL: jdbc:postgresql://db:5432/db
      PG_USER: postgres
      PG_PASSWORD: admin
      KAFKA_HOST: kafka:9092
      KAFKA_TOPIC: lot4_messages
      KAFKA_TOPIC_NOTIFY: lot4_notify
      KAFKA_GROUP_NOTIFY: lot4_group_notify
      GRAYLOG_HOST: graylog
      GRAYLOG_PORT: '12201'
      REDIS_HOST: redis
      REDIS_PORT: '6379'
    ports:
      - '8082:8080'
    links:
      - db
      - kafka
      - graylog

  sender-app:
    image: 'sender-app:latest'
    environment:
      KAFKA_HOST: kafka:9092
      KAFKA_TOPIC: lot4_messages
      KAFKA_NAME_GROUP: lot4_senders
      GRAYLOG_HOST: graylog
      GRAYLOG_PORT: '12201'
    ports:
      - '8083:8080'
    links:
      - kafka
      - graylog

  statistic-app:
    image: 'statistic-app:latest'
    environment:
      PG_URL: jdbc:postgresql://db:5432/db
      PG_USER: postgres
      PG_PASSWORD: admin
      GRAYLOG_HOST: graylog
      GRAYLOG_PORT: '12201'
    ports:
      - '8084:8080'
    links:
      - db
  front-app:
    image: 'front-app:1.0.0'
    ports:
      - '4200:4200'
    links:
      - statistic-app

  mongodb:
    image: mongo:3

  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    links:
      - mongodb

  graylog:
    hostname: graylog
    image: graylog/graylog:3.1
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:9999/
      - GRAYLOG_WEB_ENDPOINT_URI=http://0.0.0.0:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 9999:9000
      - 514:514
      - 514:514/udp
      - 12201:12201
      - 12201:12201/udp

  redis:
    hostname: redis
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
