version: '2'
services:
  zookeeper:
    container_name: KKTT-DEV-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - '2182:2181'
  kafka:
    container_name: KKTT-DEV-inside_kafka
    image: 'wurstmeister/kafka:2.12-2.2.1'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_CREATE_TOPICS: "lot4-messages"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
  recever-app:
    container_name: recever-app
      image: 'receiver-app:1.0.0'
      environment:
        KAFKA_HOST: kafka:9092
        PG_URL: db:5432
