version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2182:2181'
  kafka:
    image: 'wurstmeister/kafka:2.12-2.2.1'
    ports:
      - '9092:9092'
      - '1099:1099'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      JMX_PORT: '1099'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  sender-app:
    image: 'sender-app:latest'
    environment:
      KAFKA_HOST: kafka:9092
      KAFKA_TOPIC: lot4-messages
      GRAYLOG_HOST: graylog
      GRAYLOG_PORT: '12201'
    ports:
      - '8083:8080'
    depends_on:
      - kafka
      - graylog

  mongodb:
    image: mongo:3

  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    links:
      - mongodb

  graylog:
    hostname: graylog
    image: graylog/graylog:3.1
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:9999/
      - GRAYLOG_WEB_ENDPOINT_URI=http://0.0.0.0:9000/
      #- GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 9999:9000
      - 514:514
      - 514:514/udp
      - 12201:12201
      - 12201:12201/udp
