spring:
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/db}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:admin}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true