receiver:
  schedule:
    rate: 15
kafka:
  bootstrapAddress: ${KAFKA_HOST:localhost:2182}
  topic: ${KAFKA_TOPIC:lot4-messages}
spring:
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/db}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
  flyway:
    enabled: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
