server:
  port: 8080

spring:
  application:
    name: statistic
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/db}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:admin}
  flyway:
    enabled: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
