kafka:
  bootstrapAddress: ${KAFKA_HOST:localhost:9092}
  topic: ${KAFKA_TOPIC:lot4_notify}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
